### ISSUE TITLE
自动化测试增加JWT验证，或者去除头部绑定参数时引入的双引号。

### ISSUE THREAD

**Issue by jonechenug** [eolinker/eoLinker-API-Management-for-PHP#14]
假设有一个接口的验证为JWT，则头部应该有 Authorization: bearer token。
但是目前的版本并不支持 Basic Auth 之外的认证方式。
另一种途径是头部中绑定其他测试结果的参数，如 Authorization: bearer <response[0].result.access_token> ，但是在替换<response[0].result.access_token> 时会引入双引号，比如原先access_token是123456，则请求中Authorization会变成 bearer  "123456"

**Comment by rohochan** [comment]
我试了下,可以,用的关联自动匹配的字段没有双引号
