### ISSUE TITLE
功能建议：swagger 动态同步接口

### ISSUE THREAD

**Issue by AloneFire** [eolinker/eoLinker-API-Management-for-PHP#23]
Swagger 接口文档多数情况下，都是由框架自动生成的，开发的服务会有一个固定的swagger json 地址，希望可以动态持续地同步该接口地址，这样就大大的节省了手动录入时间

**Comment by eolinker** [comment]
抱歉，eolinker和swagger属于两套系统，无法做跨系统间的兼容。
